name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      statuses: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version: '1.25'

      - name: Run tests
        run: make test

      - name: Verify coverage report
        run: test -s coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests
          name: go-kv-unit
          fail_ci_if_error: true
          verbose: true
          override_commit: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          override_pr: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || '' }}
